# -*- coding: utf-8 -*-
"""pertemuan 11 nafis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wgwvcAsJeZHpFTyJUtY4uYi0mTi1s_k4
"""

# Program Sistem Manajemen Perpustakaan Sederhana

perpustakaan = {}

def tambah_buku():
    key = input("Masukkan kode buku (KEYS): ")
    judul = input("Masukkan judul buku: ")
    penulis = input("Masukkan nama penulis: ")
    tahun = input("Masukkan tahun terbit: ")
    tanggal_terakhir = input("Masukkan tanggal terakhir pinjam (YYYY-MM-DD): ")
    status = input("Masukkan status (TERSEDIA / TIDAK): ").upper()

    perpustakaan[key] = {
        "JUDUL BUKU": judul,
        "PENULIS": penulis,
        "TAHUN TERBIT": tahun,
        "TANGGAL TERAKHIR PINJAM": tanggal_terakhir,
        "STATUS": status
    }
    print(f"\nBuku '{judul}' berhasil ditambahkan!\n")

def tampilkan_buku():
    if not perpustakaan:
        print("\nBelum ada data buku.\n")
        return
    print("\n=== DAFTAR BUKU DALAM SISTEM ===")
    for key, data in perpustakaan.items():
        print(f"\nKEY: {key}")
        for info, nilai in data.items():
            print(f"{info}: {nilai}")
    print()

# Program utama
while True:
    print("=== SISTEM PERPUSTAKAAN ===")
    print("1. Tambah Buku")
    print("2. Tampilkan Buku")
    print("3. Keluar")
    pilihan = input("Pilih menu: ")

    if pilihan == "1":
        tambah_buku()
    elif pilihan == "2":
        tampilkan_buku()
    elif pilihan == "3":
        print("Terima kasih telah menggunakan sistem ini!")
        break
    else:
        print("Pilihan tidak valid.\n")