# -*- coding: utf-8 -*-
"""Praktikum Alpro 10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11uMLBWlAnlZ8136hmKxiFQKcZSbbbcfJ
"""

mahasiswa = ("Nafis Rabbani", "2505060052", "Teknologi Informasi")

mahasiswa_list = list(mahasiswa)
mahasiswa_list[2] = "Teknologi Informasi dan Elektro"
mahasiswa = tuple(mahasiswa_list)

print("NIM:", mahasiswa[1])
print("Prodi:", mahasiswa[2])

keranjang = {
    "apel": 5000,
    "pisang": 3000,
    "jeruk": 7000,
    "anggur": 15000
}

total = 0
for harga in keranjang.values():
    total += harga

for barang, harga in keranjang.items():
    print(f"Harga {barang}: Rp {harga}")

print("Total belanja: Rp", total)

## --- Looping Dictionary ---
teman_teman = {
"cup":"ucup surucup",
"tong":"sotong surotong",
"lur":"lur sedulur",
"wel":"bung towel",
}
# looping first try (yang keluar hanya key)
for teman in teman_teman:
  print(teman)
# operator untuk mengambil item
keys = teman_teman.keys()
print(keys)
for key in teman_teman.keys():
  print(teman_teman.get(key))
values = teman_teman.values()
print(values)
for value in teman_teman.values():
  print(value)
items = teman_teman.items()
print(items)
for item in teman_teman.items():
  print(item)
for key,value in teman_teman.items():
  print(f"key = {key}, value = {value}")