# -*- coding: utf-8 -*-
"""Praktikum Alpro 12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11uMLBWlAnlZ8136hmKxiFQKcZSbbbcfJ
"""

import math

# a. Luas persegi panjang
def luas_persegi_panjang(panjang, lebar):
    return panjang * lebar

# b. Volume persegi panjang
def volume_persegi_panjang(panjang, lebar, tinggi):
    return panjang * lebar * tinggi

# c. Luas lingkaran
def luas_lingkaran(jari_jari):
    return math.pi * jari_jari ** 2

# d. Volume bola
def volume_bola(jari_jari):
    return (4/3) * math.pi * jari_jari ** 3


print("=== Hitung Luas & Volume ===")

# Input dari user
p = float(input("Masukkan panjang: "))
l = float(input("Masukkan lebar: "))
t = float(input("Masukkan tinggi: "))
r = float(input("Masukkan jari-jari: "))

print("\n=== Hasil Perhitungan ===")

print(f"Luas persegi panjang = {luas_persegi_panjang(p, l)}")
print(f"Volume persegi panjang = {volume_persegi_panjang(p, l, t)}")
print(f"Luas lingkaran = {luas_lingkaran(r)}")
print(f"Volume bola = {volume_bola(r)}")