# -*- coding: utf-8 -*-
"""Pertemuan 9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1po0cIiHmv09EQfHJBB3pCZj24lGvsImg
"""

buah = ['apel', 'mangga', 'jeruk', 'anggur', 'pisang']

# a. Tambahkan 'semangka' di akhir list
buah.append('semangka')
print(buah)

# b. Sisipkan 'durian' di antara 'jeruk' dan 'anggur'
buah.insert(buah.index('anggur'), 'durian')
print(buah)

# c. Hapus 'mangga' dari list
buah.remove('mangga')
print(buah)

# d. Ubah 'pisang' menjadi 'nanas'
buah[buah.index('pisang')] = 'nanas'
print(buah)

# e. Tampilkan 3 buah pertama
print(buah[:3])

angka = [45, 12, 78, 23, 56, 89, 34]

# a. Urutkan list secara ascending
angka_asc = sorted(angka)
print("Ascending:", angka_asc)

# b. Urutkan list secara descending
angka_desc = sorted(angka, reverse=True)
print("Descending:", angka_desc)